pipeline {
    agent {
        docker {
            image 'androidsdk/android-29'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Running build'
                sh 'chmod +x gradlew && ./gradlew --no-daemon --stacktrace clean :app:assembleDevDebug :app:assembleDevDebugAndroidTest'
            }
        }
        stage('Test') {
            steps {
                echo 'Running Test'
                sh './gradlew --no-daemon --debug :app:connectedDevDebugAndroidTest'
            }
            post {
                always {
                    echo 'Running post-test'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Running Deliver'
            }
        }
    }
}