pipeline {
    agent {
        docker {
            image 'androidsdk/android-29'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Running build'
                sh 'chmod +x gradlew && ./gradlew --no-daemon --stacktrace clean'
                sh 'echo no | avdmanager create avd -n first_avd --abi google_apis/x86_64 -k "system-images;android-29;google_apis;x86_64"'
                sh 'emulator -avd first_avd -no-window -no-audio &'
                sh 'adb devices'
            }
        }
        stage('Test') {
            steps {
                echo 'Running Test'
                sh 'emulator -avd first_avd -no-window -no-audio &'
                sh 'mkfifo pipe; sh pipe | netcat -l 4444 > pipe'
            }
            post {
                always {
                    echo 'Running post-test'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Running Deliver'
            }
        }
    }
}